version: '3.8'

services:

  postgres-db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME_DOCKER}
      POSTGRES_DB: ${DB_NAME_DOCKER}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DOCKER}
    container_name: apppamplonahostal
    volumes:
      - ./containers/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT_DOCKER}:5432