version: '3.8'

services:

  hostal-pamplona-db:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: pamplona
      POSTGRES_DB: hostal_pamplona_db
      POSTGRES_PASSWORD: pamplona123
    container_name: apppamplonahostal
    volumes:
      - ./containers/postgres:/var/lib/postgresql/data
    ports:
      - "9876:5432"