spring:
  application:
    name: hostal-pamplona
  profiles:
    active: local

info:
  project-version: @project.version@
  build-timestamp: ${maven.build.timestamp}

server:
  port: 9006

springdoc:
  properties:
    organization-url: https://github.com/SebasMedina95/AppPamplonaHostal.git
    developer-name: Juan Sebastian Medina Toro.
    developer-linkedin: https://www.linkedin.com/in/juan-sebastian-medina-toro-887491249/
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true